package:
  name: smurff
  version: 0.8.1

source:
  git_url: https://github.com/ExaScience/smurff
  git_tag: v0.8.1

requirements:
  build:
    - gcc
    - openblas
  run:
    - gcc
    - openblas

about:
  home: https://github.com/ExaScience/smurff
  license:  MIT
