package:
  name: black_smurff
  version: 0.2

source:
  url: https://github.com/ExaScience/smurff/archive/1a78c49a14a44460e3d94e722083d061fcc206c8.zip

requirements:
    build:
        - python
        - setuptools
    run:
        - matrix_io
        - scipy
        - macau
        - openblas

about:
  home: https://github.com/ExaScience/smurff
  license:  MIT
