package:
  name: arrayfire-cuda
  version: "3.6.4"

source:
    git_url: https://github.com/arrayfire/arrayfire
    git_rev: v3.6.4
    sha1: 743c1dc00c6680229d8cc87d44debe5a71d15c01

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ compiler("fortran") }} # [not win]
    - cmake
  host:
    - mkl-devel
    - fftw
    - boost
    - cudnn
  run:
    - cudatoolkit


about:
  home: http://arrayfire.org/
  license: Open Source
  summary: 'ArrayFire is a high performance software library for parallel computing with an easy-to-use API. Its array based function set makes parallel programming more accessible.'
