package:
  name: smurff
  version: 0.11.2

source:
  git_url: https://github.com/ExaScience/smurff
  git_rev: v0.11.2

build:
  number: 1

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - llvm-openmp              # [osx]
  host:
    - llvm-openmp              # [osx]
    - mkl-devel
    - eigen3
    - boost
    - cython >=0.25
    - python
    - setuptools
    - numpy >=1.13
  run:
    - llvm-openmp              # [osx]
    - mkl
    - libboost
    - python
    - numpy
    - scipy
    - pandas

test:
    commands:
        - OMP_NUM_THREADS=1 $PREFIX/libexec/tests
        - OMP_NUM_THREADS=1 $PYTHON python/smurff/test/test_bpmf.py
        - OMP_NUM_THREADS=1 $PYTHON python/smurff/test/test_smurff.py
    imports:
         - smurff
    source_files:
        - python/smurff/test/test_bpmf.py
        - python/smurff/test/test_smurff.py

about:
  home: https://github.com/ExaScience/smurff
  license:  MIT
