language: cpp
os: linux
dist: xenial

env:
  - SMURFF_FLOAT_TYPE=double ALLOWED_FAILURES=0  BUILD_TYPE=Debug
  - SMURFF_FLOAT_TYPE=double ALLOWED_FAILURES=0  BUILD_TYPE=Release

addons:
  apt:
    sources:
      - sourceline: 'ppa:lkoppel/robotics'
    packages:
      - libblas-dev
      - liblapack-dev
      - liblapacke-dev
      - libviennacl-dev
      - libboost-all-dev
      - libopenmpi-dev
      - libeigen3-dev
      - libhdf5-dev

script:
    - cd "${TRAVIS_BUILD_DIR}" &&
      wget -O HighFive.tar.gz https://github.com/BlueBrain/HighFive/archive/v2.2.tar.gz && 
      tar xzf HighFive.tar.gz && 
      cd HighFive* && mkdir build && cd build && 
      cmake .. -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/prefix && 
      make -j2 && make install 

    - cd "${TRAVIS_BUILD_DIR}"
    - mkdir build && cd build
    - cmake .. 
        -DSMURFF_FLOAT_TYPE=${SMURFF_FLOAT_TYPE} 
        -DHIGHFIVE_USE_BOOST=OFF
        -DENABLE_PYTHON=OFF 
        -DCMAKE_PREFIX_PATH=${TRAVIS_BUILD_DIR}/prefix 
        -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" 
        -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/prefix 
        -DBOOST_RANDOM_VERSION=1.58
    - make -j2
    - ./bin/tests || [ $? -le $ALLOWED_FAILURES ]
