cp -r unsupported $PREFIX/include
language: cpp
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    env: BUILD_TYPE="Debug"
  - os: linux
    dist: trusty
    sudo: false
    env: BUILD_TYPE="Release"
env:
  global:
    - MAKEFLAGS="-j 2"
install:
addons:
  apt:
    packages:
#      - libopenblas-dev
      - libblas-dev
      - liblapack-dev
#      - libeigen3-dev # too old :(
      - cmake3
      - cmake3-data
script:
    - cd "${TRAVIS_BUILD_DIR}"
    - cd lib/smurff-cpp/cmake
    - ./local_eigen.sh eigen3
    - mkdir build
    - cd build
    - cmake --version
    - cmake .. -DENABLE_LAPACK=ON -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" -DCMAKE_PREFIX_PATH=../eigen3
    - make
    - make test

after_success:
  - echo "success"
 
after_failure:
  - echo "failure"
