language: cpp
os: linux
dist: xenial

env:
  - FLOAT_TYPE=float  ALLOWED_FAILURES=10 BUILD_TYPE=Debug
  - FLOAT_TYPE=float  ALLOWED_FAILURES=10 BUILD_TYPE=Release
  - FLOAT_TYPE=double ALLOWED_FAILURES=0  BUILD_TYPE=Debug
  - FLOAT_TYPE=double ALLOWED_FAILURES=0  BUILD_TYPE=Release

addons:
  apt:
    sources:
      - sourceline: 'ppa:lkoppel/robotics'
    packages:
      - libblas-dev
      - liblapack-dev
      - liblapacke-dev
      - libviennacl-dev
      - libboost-all-dev
      - libopenmpi-dev
      - libeigen3-dev

script:
    - cd "${TRAVIS_BUILD_DIR}"
    - cd cpp/cmake && mkdir build && cd build
    - cmake .. -DFLOAT_TYPE=${FLOAT_TYPE} -DENABLE_PYTHON=OFF -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" -DCMAKE_INSTALL_PREFIX=$PWD/../prefix -DENABLE_BOOST_RANDOM=ON
    - make -j2
    - ./bin/tests || [ $? -le $ALLOWED_FAILURES ]
