language: cpp
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    env: BUILD_TYPE="Debug"
  - os: linux
    dist: trusty
    sudo: false
    env: BUILD_TYPE="Release"
env:
  global:
    - MAKEFLAGS="-j 2"
install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}" && cd "${DEPS_DIR}"
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      if [[ -z "$(ls -A ${DEPS_DIR}/cmake/bin)" ]]; then
        CMAKE_URL="https://cmake.org/files/v3.9/cmake-3.9.4-Linux-x86_64.tar.gz"
        mkdir -p cmake && travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C cmake
      fi
      export PATH="${DEPS_DIR}/cmake/bin:${PATH}"
      export OMP_NUM_THREADS=1
    fi
  - wget -q https://arrayfire.s3.amazonaws.com/3.6.1/ArrayFire-v3.6.1_Linux_x86_64.sh
  - sudo chmod +x ArrayFire-v*_Linux_x86_64.sh
  - sudo ./ArrayFire-v*_Linux_x86_64.sh --exclude-subdir --prefix=/usr/local
addons:
  apt:
    packages:
#      - libopenblas-dev
      - libblas-dev
      - liblapack-dev
      - liblapacke-dev
      - libviennacl-dev
      - libboost-all-dev
      - libopenmpi-dev
#      - libeigen3-dev # too old :(
#      - cmake3
#      - cmake3-data
script:
    - cd "${TRAVIS_BUILD_DIR}"
    - cd lib/smurff-cpp/cmake
    - ./local_eigen.sh prefix >install-eigen.log
    - mkdir build
    - cd build
    - cmake --version
    - cmake .. -DENABLE_PYTHON=OFF -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" -DCMAKE_INSTALL_PREFIX=$PWD/../prefix -DENABLE_BOOST_RANDOM=ON
    - make
    - ./${BUILD_TYPE}/tests

after_success:
  - echo "success"

after_failure:
  - echo "failure"
