language: cpp
os: linux
dist: xenial

env:
  global:
    - MAKEFLAGS="-j 2"
  - SMURFF_FLOAT_TYPE=double ALLOWED_FAILURES=0  BUILD_TYPE=Debug
  - SMURFF_FLOAT_TYPE=double ALLOWED_FAILURES=0  BUILD_TYPE=Release
  - SMURFF_FLOAT_TYPE=double ALLOWED_FAILURES=0  BUILD_TYPE=RelNoOpenMP

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}" && cd "${DEPS_DIR}"
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      if [[ -z "$(ls -A ${DEPS_DIR}/cmake/bin)" ]]; then
        CMAKE_URL="https://cmake.org/files/v3.9/cmake-3.9.4-Linux-x86_64.tar.gz"
        mkdir -p cmake && travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C cmake
      fi
      export PATH="${DEPS_DIR}/cmake/bin:${PATH}"
      export OMP_NUM_THREADS=1
    fi
  - wget -q https://arrayfire.s3.amazonaws.com/3.6.1/ArrayFire-v3.6.1_Linux_x86_64.sh
  - sudo chmod +x ArrayFire-v*_Linux_x86_64.sh
  - sudo ./ArrayFire-v*_Linux_x86_64.sh --exclude-subdir --prefix=/usr/local

addons:
  apt:
    sources:
      - sourceline: 'ppa:lkoppel/robotics'
    packages:
      - libblas-dev
      - liblapack-dev
      - liblapacke-dev
      - libviennacl-dev
      - libboost-all-dev
      - libopenmpi-dev
      - libeigen3-dev
      - libhdf5-dev

script:
    - cd "${TRAVIS_BUILD_DIR}" &&
      wget -O HighFive.tar.gz https://github.com/BlueBrain/HighFive/archive/v2.2.tar.gz && 
      tar xzf HighFive.tar.gz && 
      cd HighFive* && mkdir build && cd build && 
      cmake .. -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/prefix && 
      make -j2 && make install 

    - cd "${TRAVIS_BUILD_DIR}"
    - mkdir build && cd build
    - cmake .. 
        -DSMURFF_FLOAT_TYPE=${SMURFF_FLOAT_TYPE} 
        -DENABLE_PYTHON=OFF 
        -DCMAKE_PREFIX_PATH=${TRAVIS_BUILD_DIR}/prefix 
        -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" 
        -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/prefix 
    - make -j2
    - ./bin/tests || [ $? -le $ALLOWED_FAILURES ]
