language: cpp
matrix:
  include:
  - os: linux
    dist: xenial
    sudo: false
    env: BUILD_TYPE="Debug"
  - os: linux
    dist: xenial
    sudo: false
    env: BUILD_TYPE="Release"
env:
  global:
    - MAKEFLAGS="-j 2"
install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}" && cd "${DEPS_DIR}"
addons:
  apt:
    sources:
      - ppa:lkoppel/robotics
    packages:
      - libblas-dev
      - liblapack-dev
      - liblapacke-dev
      - libboost-all-dev
      - libopenmpi-dev
      - libeigen3-dev
      - cmake
script:
    - cd "${TRAVIS_BUILD_DIR}"
    - cd lib/smurff-cpp/cmake
    - mkdir build
    - cd build
    - cmake --version
    - cmake .. -DENABLE_PYTHON=OFF -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" -DCMAKE_INSTALL_PREFIX=$PWD/../prefix -DENABLE_BOOST_RANDOM=ON
    - make
    - ./${BUILD_TYPE}/tests

after_success:
  - echo "success"

after_failure:
  - echo "failure"
