language: cpp
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
addons:
  apt:
    packages:
    - cmake3
    - cmake3-data
script:
- cd lib/smurff-cpp/cmake
- rm build -r
- mkdir build
- cd build
- cmake .. -DENABLE_OPENBLAS=ON -DCMAKE_BUILD_TYPE=Debug
