jobs:

- job: 'Ubuntu_1604_Apt'
  pool:
    vmImage: 'Ubuntu 16.04'

  strategy:
    maxParallel: 2
    matrix:
      Debug:
        build.type: 'Debug'
      Release:
        build.type: 'Release'

  steps:
    - script: |
        sudo add-apt-repository ppa:lkoppel/robotics
        sudo apt-get update
        sudo apt-get install -y ninja-build libblas-dev liblapack-dev liblapacke-dev libboost-all-dev libopenmpi-dev libeigen3-dev
      displayName: Apt install dependencies
    - script: |
        mkdir build.$(build.type)
      displayName: Make Build Directory
    - task: CMake@1
      inputs:
        workingDirectory: 'build.$(build.type)'
        cmakeArgs: '-G Ninja -DCMAKE_BUILD_TYPE=$(build.type) ../lib/smurff-cpp/cmake -DENABLE_PYTHON=OFF -DENABLE_BOOST_RANDOM=ON'
    - script: |
        cd build.$(build.type)
        ninja
      displayName: 'Run ninja'
    - script: |
        cd build.$(build.type)/$(build.type)
        ./tests
      displayName: 'Run tests'

- job: 'Conda'
  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
    - task: CondaEnvironment@1
    - script: |
        cd conda-recipes
        conda build smurff-0.14
      displayName: Build


