jobs:

- job: 'Ubuntu 16.04 Apt'
  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
    - script: |
        sudo add-apt-repository ppa:lkoppel/robotics
        sudo add-get update
        sudo apt-get install -y libblas-dev liblapack-dev liblapacke-dev libboost-all-dev libopenmpi-dev libeigen3-dev
      displayName: Apt install dependencies
    - script: |
        mkdir build.debug
        mkdir build.release
      displayName: Make Build Directories
    - task: CMake@1
      inputs:
        workingDirectory: 'build.debug'
        cmakeArgs: '-G Ninja -DCMAKE_BUILD_TYPE=Debug ../lib/smurff-cpp/cmake -DENABLE_PYTHON=OFF -DENABLE_BOOST_RANDOM=ON'
    - task: CMake@1
      inputs:
        workingDirectory: 'build.release'
        cmakeArgs: '-G Ninja -DCMAKE_BUILD_TYPE=Release ../lib/smurff-cpp/cmake -DENABLE_PYTHON=OFF -DENABLE_BOOST_RANDOM=ON'
    - script: |
        cd build.debug
        ninja
      displayName: 'Run ninja, debug'
    - script: |
        cd build.debug/Debug
        ./test '~[random]'
      displayName: 'Run tests, debug'
    - script: |
        cd build.release
        ninja
      displayName: 'Run ninja, release'
    - script: |
        cd build.release/Release
        ./tests '~[random]'
      displayName: 'Run tests, release'
