{% set name = "h5sparse" %}
{% set version = "0.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/tvandera/h5sparse/archive/v0.2.0.tar.gz"
  sha256: b7e6fbfa2f2f61adaa169a3a0a52bc6f2178f5daff8fa6d972a8dcaa7f3cc8f7

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - h5py
    - numpy
    - pip
    - python
    - scipy
    - six
  run:
    - h5py
    - numpy
    - python
    - scipy
    - six

test:
  imports:
    - h5sparse

about:
  home: "https://github.com/appier/h5sparse"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Scipy sparse matrix in HDF5."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
