{% set name = "h5sparse" %}
{% set version = "0.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/tvandera/h5sparse/archive/v0.2.0.tar.gz"
  sha256: ce3176f6772ddd22ec3349cf10533fbfd6e692c5f84acb4c01f02002cfe0f2da

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - h5py
    - numpy
    - python
    - scipy
    - six
    - pip
    - nose
    - coverage
  run:
    - h5py
    - numpy
    - python
    - scipy
    - six

test:
  requires:
    - nose
  command:
    - nosetest

about:
  home: "https://github.com/appier/h5sparse"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Scipy sparse matrix in HDF5."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
