package:
  name: matrix_io
  version: 0.5

source:
  url: https://github.com/ExaScience/smurff/archive/b4d3fb311aa3539d40b7dc255b01e554d6d6bbd4.zip

build:
    number: 1
    noarch: python

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - scipy

test:
    commands:
        - $PYTHON python/matrix_io/test/test_matrix_io.py
    imports:
        - matrix_io
    source_files:
        - python/matrix_io/test/test_matrix_io.py

about:
  home: https://github.com/ExaScience/smurff
  license:  MIT
