package:
  name: smurff
  version: 0.10.2

source:
  git_url: https://github.com/ExaScience/smurff
  git_rev: v0.10.2

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - llvm-openmp              # [osx]
  host:
    - eigen3
    - intel-openmp 2017.*      # [not linux] 
    - mkl 2017.*
    - libboost
    - cython >=0.25
    - python
    - setuptools
    - numpy >=1.13
  run:
    - intel-openmp 2017.*      # [not linux]
    - mkl 2017.*
    - llvm-openmp              # [osx]
    - libboost
    - python
    - numpy
    - scipy
    - pandas

test:
    commands:
        - OMP_NUM_THREADS=1 $PREFIX/libexec/tests
        - OMP_NUM_THREADS=1 $PYTHON python/smurff/test/test_bpmf.py
        - OMP_NUM_THREADS=1 $PYTHON python/smurff/test/test_smurff.py
    imports:
        - smurff
    source_files:
        - python/smurff/test/test_bpmf.py
        - python/smurff/test/test_smurff.py

about:
  home: https://github.com/ExaScience/smurff
  license:  MIT
