package:
  name: black_smurff
  version: 0.1

source:
  git_url: https://github.com/ExaScience/smurff

requirements:
    run:
        - scipy
        - macau
        - openblas

about:
  home: https://github.com/ExaScience/smurff
  license:  MIT
