{% set data = load_setup_py_data(setup_file='../../setup.py', from_recipe_dir=True) %}

package:
  name: smurff
  version: {{ data.get('version') }}

source:
  path: ../..

build:
    number: 1

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - llvm-openmp             # [osx]
  host:
    - llvm-openmp             # [osx]
    - intel-openmp
    - mkl-devel
    - eigen3
    - boost
    - libboost {{ libboost }}
    - pybind11
    - highfive =2.2
    - h5py
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - numpy >=1.13
  run:
    - python {{ python }}
    - intel-openmp
    - mkl
    - libboost {{ libboost }}
    - numpy
    - scipy
    - pandas
    - scikit-learn
    - hdf5
    - h5py
    - h5sparse >=0.2.0

about:
  home: https://github.com/ExaScience/smurff
  license:  MIT
