package:
  name: smurff
  version: 0.13.1

source:
  git_url: https://github.com/ExaScience/smurff
  git_rev: v0.13.1

build:
    number: 1

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - llvm-openmp             # [osx]
  host:
    - llvm-openmp            # [osx]
    - intel-openmp
    - mkl-devel
    - eigen3
    - boost
    - cython >=0.25
    - python {{ python }}
    - setuptools
    - numpy >=1.13
  run:
    - llvm-openmp              # [osx]
    - intel-openmp
    - mkl
    - libboost
    - python
    - numpy
    - scipy
    - pandas
    - scikit-learn
    - matrix_io

about:
  home: https://github.com/ExaScience/smurff
  license:  MIT
