package:
  name: eigen3
  version: "3.3.7"

source:
  fn: eigen3-3.3.7.tar.gz
  url: https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.tar.gz
  sha1: 3e8ab94ff389ae4b3103f5dda77c826d85b9c1d5

requirements:
  build:
    - cmake
    - {{compiler("cxx")}}
    
test:
  files:
    - test.cc

build:
  number: 2

about:
  home: http://eigen.tuxfamily.org/
  license: MPL2
  summary: 'C++ template library for linear algebra'
