package:
  name: eigen3
  version: "3.3.7"

source:
  fn: eigen3-3.3.7.tar.gz
  url: http://bitbucket.org/eigen/eigen/get/3.3.7.tar.gz
  sha1: 743c1dc00c6680229d8cc87d44debe5a71d15c01

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ compiler("fortran") }} # [not win]
    - cmake
    - mkl-devel                 # [not win]

test:
  files:
    - test.cc

about:
  home: http://eigen.tuxfamily.org/
  license: MPL2
  summary: 'C++ template library for linear algebra'
