package:
  name: smurff
  version: 0.99.0

source:
  # git_url: https://github.com/ExaScience/smurff
  # git_url: https://github.com/ExaScience/smurff
  # git_tag: develop
  path: ../..

build:
    number: 1

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - llvm-openmp             # [osx]
  host:
    - llvm-openmp             # [osx]
    - intel-openmp
    - mkl-devel
    - eigen3
    - boost
    - libboost {{ libboost }}
    - pybind11
    - highfive
    - h5py
    - python {{ python }}
    - setuptools
    - numpy >=1.13
  run:
    - intel-openmp
    - mkl
    - libboost
    - numpy
    - scipy
    - pandas
    - scikit-learn
    - hdf5
    - h5py
    - h5sparse >=0.2.0

about:
  home: https://github.com/ExaScience/smurff
  license:  MIT
