package:
  name: macau
  version: 0.5.0

source:
  git_url: https://github.com/jaak-s/macau
  git_tag: v0.5.0

requirements:
  build:
    - {{ compiler('cxx') }}    # [not win]
    - {{ compiler('c') }}      # [not win]
    - llvm-openmp              # [osx]
    - cython
    - python
    - setuptools
    - openblas
    - numpy
    - scipy
    - pandas
  run:
    - llvm-openmp             # [osx]
    - python
    - openblas
    - numpy
    - scipy
    - pandas

about:
  home: https://github.com/jaak-s/macau
  license:  MIT
