package:
  name: matrix_io
  version: 0.1

source:
  url: https://github.com/ExaScience/smurff/archive/master.zip

build:
    number: 1
    noarch: python

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - scipy

about:
  home: https://github.com/ExaScience/smurff
  license:  MIT
