package:
  name: matrix_io
  version: 0.1

source:
  git_url: https://github.com/ExaScience/smurff

requirements:
    build:
        - python
        - setuptools
    run:
        - scipy

about:
  home: https://github.com/ExaScience/smurff
  license:  MIT
