package:
  name: smurff
  version: 0.10.3

source:
  git_url: https://github.com/ExaScience/smurff
  git_rev: v0.10.3

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - llvm-openmp              # [osx]
  host:
    - eigen3
    - mkl-devel 2017.*
    - boost
    - cython >=0.25
    - python
    - setuptools
    - numpy
  run:
    - intel-openmp 2017.*
    - mkl 2017.*
    - llvm-openmp              # [osx]
    - libboost
    - python
    - numpy
    - scipy
    - pandas

test:
    commands:
        - $PREFIX/libexec/tests
    imports:
        - smurff

about:
  home: https://github.com/ExaScience/smurff
  license:  MIT
