package:
  name: smurff
  version: 0.10.3

source:
  git_url: https://github.com/ExaScience/smurff
  git_rev: v0.10.3


build:
  number: 3
  features:
    - nomkl    [nomkl]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - llvm-openmp             [osx]
  host:
    - eigen3
    - mkl-devel 2017.*        [not nomkl]
    - openblas                [linux and nomkl]
    - llvm-openmp             [osx]
    - boost
    - cython >=0.25
    - python
    - setuptools
    - numpy
  run:
    - mkl 2017.*             [not nomkl]
    - openblas                [linux and nomkl]
    - llvm-openmp             [osx]
    - libboost
    - python
    - numpy
    - scipy
    - pandas

test:
    commands:
        - $PREFIX/libexec/tests
    imports:
        - smurff

about:
  home: https://github.com/ExaScience/smurff
  license:  MIT
