package:
  name: smurff
  version: 0.15.0

source:
   git_url: https://github.com/ExaScience/smurff
   git_rev: v0.15.0

build:
   number: 1

requirements:
   build:
     - cmake
     - {{ compiler('cxx') }}
     - {{ compiler('c') }}
     - llvm-openmp              # [osx]
   host:
     - llvm-openmp              # [osx]
     - intel-openmp
     - mkl-devel
     - eigen3
     - boost
     - cython >=0.25
     - python {{ python }}
     - setuptools
     - numpy >=1.13
   run:
     - llvm-openmp              # [osx]
     - intel-openmp
     - mkl
     - libboost
     - python
     - numpy >=1.13
     - scipy
     - pandas
     - scikit-learn
     - matrix_io

test:
    commands:
        - OMP_NUM_THREADS=1 $PREFIX/libexec/tests  '~[random]'
        - OMP_NUM_THREADS=1 $PYTHON python/smurff/test/test_bpmf.py
        - OMP_NUM_THREADS=1 $PYTHON python/smurff/test/test_smurff.py
    imports:
         - smurff
    source_files:
        - python/smurff/test/test_bpmf.py
        - python/smurff/test/test_smurff.py

about:
   home: https://github.com/ExaScience/smurff
   license:  MIT
