CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.9.sdk        # [osx]

python:
    - 3.6
    - 3.7
    - 3.8

blas_impl:
    - openblas
    - mkl

numpy:
    - 1.16      

pin_run_as_build:
  libboost: x.x
  numpy: x.x
  hdf5: x.x.x
