CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.9.sdk        # [osx]

c_compiler:
  - vs2017                     # [win]

cxx_compiler:
  - vs2017                     # [win]

python:
    - 3.6
    - 3.7

pin_run_as_build:
  boost: x.x
  numpy: x.x
