CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.9.sdk        # [osx]

python:
    - 3.6
    - 3.7
    - 3.8

libboost:
    - 1.67

numpy:
    - 1.18

blas_impl:
    - openblas
    - mkl

pin_run_as_build:
  libboost: x.x
  numpy: x.x
