package:
  name: viennacl
  version: 1.7.1

source:
  git_url: https://github.com/viennacl/viennacl-dev
  git_tag: release-1.7.1
  
requirements:
  build:
    - {{ compiler("cxx") }}
    - cmake

  host:
    - libboost
    - eigen3
    - cudatoolkit

  run:
    - eigen3
    - cudatoolkit

about:
  home: http://viennacl.sourceforge.net/
