package:
  name: black_smurff
  version: 0.4

source:
  url: https://github.com/ExaScience/smurff/archive/black_smurff-v0.4.tar.gz

build:
    noarch: python

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - matrix_io
        - scipy
        - macau

about:
  home: https://github.com/ExaScience/smurff
  license:  MIT
