steps:
    - task: CondaEnvironment@1
    - script: |
        cd conda-recipes
        conda create -n smurff-builder conda-build
        conda activate smurff-builder
        conda build -c vanderaa smurff-latest
      displayName: Build