steps:
    - task: CondaEnvironment@1
      inputs:
        updateConda: true
        packageSpecs: 'conda-build' # Optional
    - script: |
        cd conda-recipes
        conda build -c vanderaa smurff-latest
      displayName: Build