package:
  name: smurff
  version: 0.6.2

source:
  git_url: https://github.com/ExaScience/smurff
  git_tag: v0.6.2

requirements:
  build:
    - {{ compiler('cxx') }}    # [not win]
    - llvm-openmp              # [osx]
    - openblas
  run:
    - llvm-openmp              # [osx]
    - openblas

about:
  home: https://github.com/ExaScience/smurff
  license:  MIT
