package:
  name: smurff
  version: latest

source:
  url: https://github.com/ExaScience/smurff/archive/master.zip

requirements:
  build:
    - cmake
    - wget
    - {{ compiler('cxx') }}    # [not win]
    - llvm-openmp              # [osx]
    - openblas
  run:
    - llvm-openmp              # [osx]
    - openblas

test:
    commands:
        $PREFIX/libexec/tests


about:
  home: https://github.com/ExaScience/smurff
  license:  MIT
