package:
  name: smurff
  version: {{ environ.get("GIT_DESCRIBE_TAG", "0.99.9").lstrip("v") }}

source:
  path: ../..

build:
    number: {{ GIT_DESCRIBE_NUMBER }}

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - llvm-openmp             # [osx]
  host:
    - llvm-openmp            # [osx]
    - intel-openmp
    - mkl-devel
    - eigen3
    - boost
    - cython >=0.25
    - python {{ python }}
    - setuptools
    - numpy >=1.13
  run:
    - llvm-openmp              # [osx]
    - intel-openmp
    - mkl
    - libboost
    - python
    - numpy
    - scipy
    - pandas
    - scikit-learn
    - matrix_io

about:
  home: https://github.com/ExaScience/smurff
  license:  MIT
