package:
  name: smurff
  version: latest

source:
  git_url: https://github.com/ExaScience/smurff

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}    # [not win]
    - llvm-openmp              # [osx]
    - eigen3
    - boost 
    - numpy
  run:
    - llvm-openmp              # [osx]
    - boost 

test:
    commands:
        # OMP_NUM_THREADS=1 $PREFIX/libexec/tests


about:
  home: https://github.com/ExaScience/smurff
  license:  MIT
