package:
  name: smurff
  version: latest

source:
  git_url: https://github.com/ExaScience/smurff

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - llvm-openmp              # [osx]
  host:
    - eigen3
    - llvm-openmp              # [osx]
    - mkl
    - libboost
    - cython >=0.25
    - python
    - setuptools
    - numpy
  run:
    - mkl 
    - llvm-openmp              # [osx]
    - libboost
    - python
    - numpy
    - scipy
    - pandas

test:
    commands:
        - OMP_NUM_THREADS=1 $PREFIX/libexec/tests
        - OMP_NUM_THREADS=1 $PYTHON python/smurff/test/test_bpmf.py
        - OMP_NUM_THREADS=1 $PYTHON python/smurff/test/test_smurff.py
    imports:
        - smurff
    source_files:
        - python/smurff/test/test_bpmf.py
        - python/smurff/test/test_smurff.py

about:
  home: https://github.com/ExaScience/smurff
  license:  MIT
