package:
  name: smurff
  version: 0.5.0

source:
  git_url: https://github.com/ExaScience/smurff
  git_tag: v0.5.0-excape

requirements:
  build:
    - {{ compiler('cxx') }}    # [not win]
    - llvm-openmp
    - openblas
  run:
    - llvm-openmp
    - openblas

about:
  home: https://github.com/ExaScience/smurff
  license:  MIT
